{"name": "Ошибка при неверном логине", "status": "passed", "description": "Проверяем, что нельзя авторизоваться с несуществующим логином", "steps": [{"name": "Отправка запроса на авторизацию с несуществующим логином", "status": "passed", "steps": [{"name": "Авторизация курьера", "status": "passed", "parameters": [{"name": "login", "value": "'none_login'"}, {"name": "password", "value": "'b)21sWSwJY'"}], "start": 1755634153110, "stop": 1755634153186}], "start": 1755634153110, "stop": 1755634153186}, {"name": "Проверка статуса ответа: должен быть 404 и в теле ответа есть сообщение об ошибке: \"Учетная запись не найдена\"", "status": "passed", "start": 1755634153186, "stop": 1755634153186}], "start": 1755634153110, "stop": 1755634153186, "uuid": "89a538a6-c2fb-4c97-b05a-f985585f8298", "historyId": "1938d255e5baf1ec1d1fcc23e92a80ab", "testCaseId": "1938d255e5baf1ec1d1fcc23e92a80ab", "fullName": "tests.test_auth_courier.TestAuthCourier#test_failure_auth_courier_invalid_login", "labels": [{"name": "feature", "value": "API: Авторизация курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_courier"}, {"name": "subSuite", "value": "TestAuthCourier"}, {"name": "host", "value": "DESKTOP-RUV96V5"}, {"name": "thread", "value": "24996-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_courier"}], "titlePath": ["tests", "test_auth_courier.py", "TestAuthCourier"]}