{"name": "Ошибка при неверном логине", "status": "passed", "description": "Проверяем, что нельзя авторизоваться с несуществующим логином", "steps": [{"name": "Отправка запроса на авторизацию с несуществующим логином", "status": "passed", "steps": [{"name": "Авторизация курьера", "status": "passed", "parameters": [{"name": "login", "value": "'none_login'"}, {"name": "password", "value": "'^^(LukJYD8'"}], "start": 1755540087388, "stop": 1755540087459}], "start": 1755540087388, "stop": 1755540087459}, {"name": "Проверка статуса ответа: должен быть 404 и в теле ответа есть сообщение об ошибке: \"Учетная запись не найдена\"", "status": "passed", "start": 1755540087459, "stop": 1755540087459}], "start": 1755540087388, "stop": 1755540087459, "uuid": "e3210d7a-264e-409b-bab9-e22d4e6aa24a", "historyId": "1938d255e5baf1ec1d1fcc23e92a80ab", "testCaseId": "1938d255e5baf1ec1d1fcc23e92a80ab", "fullName": "tests.test_auth_courier.TestAuthCourier#test_failure_auth_courier_invalid_login", "labels": [{"name": "feature", "value": "API: Авторизация курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_courier"}, {"name": "subSuite", "value": "TestAuthCourier"}, {"name": "host", "value": "DESKTOP-RUV96V5"}, {"name": "thread", "value": "26960-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_courier"}], "titlePath": ["tests", "test_auth_courier.py", "TestAuthCourier"]}